web:
    image: nginx:1.9.2
    ports:
      - "28684:80"
    volumes:
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    links:
      - php

php:
  build: php-fpm
  links:
    - db:mysqlpsm

db:
  image: mysql:5.7.7
  volumes:
   - ./mysql/mysql-db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=mysecretpassword
   - MYSQL_DATABASE=phpservermon
   - MYSQL_USER=phpservermon
   - MYSQL_PASSWORD=phpservermon
  expose:
   - 3306
