web:
  image: tutorial/nginx
  ports:
    - "8080:80"
  volumes:
    - ./src/public:/var/www/public
    - ./src/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php

php:
  image: nmcteam/php56
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src/public:/var/www/public
    - ./etc-cron.d-tab-for-phpfpm.txt:/etc/cron.d/phpservermon
  links:
    - db

db:
  image: sameersbn/mysql
  volumes:
   - ./mysql-db:/var/lib/mysql
  environment:
   - DB_NAME=phpservermon
   - DB_USER=phpservermon
   - DB_PASS=phpservermon
